### ISSUE TITLE
The game failed with debugify and forge 47.2.x

### ISSUE THREAD

**Issue by liangmoe** [Sinytra/ForgifiedFabricAPI#100]
### Describe the bug

Debugify wont boot with newer version of forge

### Steps to reproduce

change forge version from 47.1.3 to 47.2.0 or 47.2.20, crashed

### Logs

latest.log: https://mclo.gs/e9TYwk2

### Additional context

also console's log: https://paste.atlauncher.com/view/badf782c-eb72-4f8e-a6f5-16dbf073f979

**Comment by Su5eD** [comment]
Please use Forge 47.1.3

**Comment by liangmoe** [comment]
Oh, i saw there is a announcement form [a discord messege](https://discord.com/channels/1141048834177388746/1142025823319240726/1176191410223972383) so i thought i can make a issue tracker here, mb
