### ISSUE TITLE
CTD at lauunch with v 0.92.0

### ISSUE THREAD

**Issue by glea94** [Sinytra/ForgifiedFabricAPI#101]
### Describe the bug

CTD

### Steps to reproduce

1.update to v 0.92.0
2.launch tthe game
3.CTD

### Logs

https://mclo.gs/JFMwUMI

**Comment by Su5eD** [comment]
Fixed in [0.92.0+1.11.1+1.20.1](https://modrinth.com/mod/forgified-fabric-api/version/0.92.0+1.11.1+1.20.1).
