### ISSUE TITLE
Crashing with optifine 

### ISSUE THREAD

**Issue by kirbyc00** [Sinytra/ForgifiedFabricAPI#104]
### Describe the bug

game crashes with optifine 

### Steps to reproduce

1. Have optifine and forgified fabric api mods installed in minecraft 
2. open minecraft
3.
...

### Logs

https://mclo.gs/7ris6q3

### Additional context

https://mclo.gs/7ris6q3 my crash log is here 
thanks

**Comment by kakashi1464** [comment]
Use embeddium and oculus

**Comment by kirbyc00** [comment]
https://mclo.gs/T1pEKPT [](https://mclo.gs/T1pEKPT) this is what happens when i add those two mods

**Comment by kakashi1464** [comment]
> https://mclo.gs/T1pEKPT This is what happens when i add those two mods

Use the forge version of the embeddium, not the fabric one

**Comment by kakashi1464** [comment]
Also you didn't remove optifine

**Comment by kirbyc00** [comment]
thank you it worked you're smart

**Comment by kirbyc00** [comment]
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/161279383/5e21a7a4-b282-4913-a220-05ad06400a54)
having this weird blurry visual glitch now. i tried to lower the render quality but it doesn't seem to have that in the settings without optifine.
anyway to fix this?
