### ISSUE TITLE
Crash at start.

### ISSUE THREAD

**Issue by Starexify** [Sinytra/ForgifiedFabricAPI#11]
### Describe the bug

The last version of the mod crashes at run

### Steps to reproduce

1. Istall the mod, put it in the mods folder.
2. Run minecraft Forge-47.0.49 1.20.1 
3. Crashed

### Logs

https://pastebin.com/qgTV8NAM

### Additional context

I tried without any other mods besides this mod. It crashes sadly
Version of the mod -> Forgified Fabric API 0.86.1+1.6.1+1.20.1

Sorry if this was reported or I did a mistake I just wonder why it doesnt work.

**Comment by Su5eD** [comment]
Try again using forge `47.1.3`

**Comment by Starexify** [comment]
Oh I had the old forge version, I forgot to check if a new version is up it works now, I'll close this now, thanks
