### ISSUE TITLE
Empty chests on server

### ISSUE THREAD

**Issue by YShadowMY** [Sinytra/ForgifiedFabricAPI#111]
### Describe the bug

Occurs when opening a new chest

### Steps to reproduce

1. Launch server on Magma Maintained with FFAPI and Connector
2. Find any chest and try to open 
3. Chest should be empty 

### Logs

https://gist.github.com/YShadowMY/3ccba24758e27a3554173ec5e14a6799

### Additional context

tested on Magma Maintained server
it works normally when only Connector is present but adding FFAPI breaks loot in chests

**Comment by Su5eD** [comment]
Sorry, as explained in our [FAQ](https://sinytra.org/docs/connector/faq), we don't support unofficial minecraft server implementations. If you can reproduce this issue on the official minecraft server, please let us know.
