### ISSUE TITLE
Will cause the mod of external audio sources to fail

### ISSUE THREAD

**Issue by Busyfox123** [Sinytra/ForgifiedFabricAPI#126]
### Describe the bug

Will cause the mod of external audio sources to fail

### Steps to reproduce

When I try to use some modules that can retrieve music playback from the internet, they all fail and won't play audio
Whether it's plugins or mod
Testing only in the environment of Sinytra
Use the latest version

**Comment by Su5eD** [comment]
> When I try to use some modules that can retrieve music playback from the internet

please provide exact details

**Comment by Busyfox123** [comment]
Net Music
https://www.curseforge.com/minecraft/mc-mods/net-music
Whether it's this or other mod with similar functions
When attempting to play music using an external audio source, it will fail
When I delete the Sinytra Connector, it will return to normal again

**Comment by Su5eD** [comment]
> When I delete the Sinytra Connector, it will return to normal again

Is this about Connector or FFAPI?

**Comment by Busyfox123** [comment]
> > 当我删除 Sinytra Connector 后，它又恢复正常了
> 
> 这是关于连接器或FFAPI吗？

yeah Tested in an environment with only Sinytra Connector
videoplayer Also unable to play
https://www.curseforge.com/minecraft/mc-mods/video-player

**Comment by schindlershadow** [comment]
this seems to be fixed in 2.0.15
