### ISSUE TITLE
Exception while adding particle

### ISSUE THREAD

**Issue by KirboSoftware** [Sinytra/ForgifiedFabricAPI#13]
### Describe the bug

Crashes upon wandering the world

### Steps to reproduce

1. Run a client with just Forgified Fabric Api
2. Create a world
3. Wander around
4. Crash

### Logs

https://pastebin.com/A1QAdA4J

### Additional context
This is soley with FFA, I tried running it with your other mod connector as well, but experienced the same issue sadly and wanted to pin the issue

**Comment by Su5eD** [comment]
From a similar issue on Connector's repo:
> Seems to be caused by Forge adding a new [tint hook](https://github.com/MinecraftForge/MinecraftForge/commit/a4bef828366527c93286a7ed7a5a02ebfd6813b2#diff-2c2475fb91e2483e76346183e062f74c8c7c2f64022dbfb9bb531aca29ea8283R8) which removes the call to BlockState#isOf, breaking our mixin. NeoForge seems to have applied the commit, too.

My plan is to cap the FFAPI Forge version range on `47.1.3`, which has become the "status quo" version mods are staying on after the Forge/Neo split. It's likely the best way to maintain compatibility until the next mc version.

**Comment by KirboSoftware** [comment]
Alright thanks for notifying. I will test on that forge version and see if it still gives issues

**Comment by Su5eD** [comment]
Released FFAPI `0.86.1+1.8.1+1.20.1` which no longer crashes on never Forge versions, allowing FML to show the loading error screen with the version range mismatch.
