### ISSUE TITLE
Frostiful Incompat

### ISSUE THREAD

**Issue by Caleboreo1** [Sinytra/ForgifiedFabricAPI#132]
### Describe the bug

Frostiful will crash when the mod count exceeds a specific amount.

### Steps to reproduce

1. load in frostiful along with 714 other mods.
2. the loading errors out.
3. crash.
...

### Logs

https://mclo.gs/dZ1IAQI

### Additional context

It's not a mod incompat either. as soon as the mod count exceeds 713 mods, (doesn't matter which mod gets added), the game will crash. unless if this is reproducible on fabric, I believe this is an issue with FFAPI.

**Comment by Su5eD** [comment]
Frostiful is a Fabric mod. For reporting issues related to Connector, please see our guide at https://sinytra.org/docs/connector#-help-and-support
