### ISSUE TITLE
Legacy 4J and Forgified Fabric on 1.20.1 do not work together.

### ISSUE THREAD

**Issue by psychoshay** [Sinytra/ForgifiedFabricAPI#135]
Here is the pastebin:
[https://pastebin.com/BrMrJgGd](https://github.com/Sinytra/ForgifiedFabricAPI/issues/url)

**Comment by psychoshay** [comment]
That is the logs with only forgified fabric and legacy 4J together.

**Comment by Su5eD** [comment]
Please use a paste site to upload logs, this way it's unreadable

**Comment by psychoshay** [comment]
[[10Jul2024 095107.843] [mainINFO] [.txt](https://github.com/user-attachments/files/16159202/10Jul2024.095107.843.mainINFO.txt)

Here is a .txt file hope that helps

**Comment by psychoshay** [comment]
Is this possibly the main issue?:

[main/FATAL] [mixin/]: Mixin prepare for mod fabric_recipe_api_v1 failed preparing ingredient.IngredientMixin in fabric-recipe-api-v1.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: fabric-recipe-api-v1.mixins.json:ingredient.IngredientMixin from mod fabric_recipe_api_v1 target net.minecraft.world.item.crafting.Ingredient **was loaded too early.**

**Comment by psychoshay** [comment]
Here is the pastebin:
[https://pastebin.com/BrMrJgGd](url)

**Comment by Cixon** [comment]
> Please use a paste site to upload logs, this way it's unreadable

@Su5eD 
hey friend, here's more info: https://github.com/Sinytra/ForgifiedFabricAPI/issues/136#issuecomment-2221837913

**Comment by Cixon** [comment]
bump

**Comment by psychoshay** [comment]
> bump

bumped

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
