### ISSUE TITLE
Legacy4J and Sinytra ForgifiedFabricAPI launch but cannot load or create worlds.

### ISSUE THREAD

**Issue by psychoshay** [Sinytra/ForgifiedFabricAPI#136]
Here is the log in a pastebin. Neoforge seems to work with Legacy4J and Forgified Fabric much better than regular forge.
[https://pastebin.com/t1bV9x5U](url)

**Comment by Cixon** [comment]
oh man, you beat me to it. here's some more crash-logs:
[crash-2024-07-10_20.48.48-client.txt](https://github.com/user-attachments/files/16170524/crash-2024-07-10_20.48.48-client.txt)

latest-log (line 235):
[latest.log](https://github.com/user-attachments/files/16170527/latest.log)

**Comment by Cixon** [comment]
also dupe of #135

**Comment by Su5eD** [comment]
Right, duplicate of #135

**Comment by psychoshay** [comment]
Ah.. So this isn't fixable?

**Comment by Cixon** [comment]
> Ah.. So this isn't fixable?

I'm sure there's a work around, it's just there's no point in posting the issue twice.
I did make sure to also add more context to the bug by contributing my [logs and crashes](https://github.com/Sinytra/ForgifiedFabricAPI/issues/136#issuecomment-2221837913). Please allow some time and pay attention to issue #135 instead.

**Comment by psychoshay** [comment]
Ah okay sorry. I thought it was different because this issue is about Neoforge and #135 is about regular forge
