### ISSUE TITLE
1.16.5 support for players with old hardware (OpenGL 2.0 hardware)

### ISSUE THREAD

**Issue by Night-423** [Sinytra/ForgifiedFabricAPI#139]
It would be nice if players with old hardware(OpenGL 2.0 hardware) can also play, if there is a version of this mod worked for 1.16.5 then players like me could play as well!

**Comment by Su5eD** [comment]
As explained in our FAQ, no official backports are planned. However, since this is open source software, anyone is free to make one themselves. Please see https://sinytra.org/docs/connector/faq for more information.
