### ISSUE TITLE
1.20.1: Refined Storage crashes in certain conditions

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/ForgifiedFabricAPI#149]
[crash-2024-08-14_18.49.50-client.txt](https://github.com/user-attachments/files/16622737/crash-2024-08-14_18.49.50-client.txt)

[crash-2024-08-13_11.03.39-client.txt](https://github.com/user-attachments/files/16622740/crash-2024-08-13_11.03.39-client.txt)

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
