### ISSUE TITLE
1.21 Neoforge - in-game music won't play

### ISSUE THREAD

**Issue by Charleychar** [Sinytra/ForgifiedFabricAPI#150]
**Description**

In my music and sound settings, everything is up to 100%, but neither menu music, in-game music, nor vanilla music discs will play. I've also tried using the command /playsound which can play some ambient sounds, but not any music.

**Recreation - sort of**

I wasn't sure which mod might be causing this issue, because I have quite a few, but through a process of elimination I found that this only happens when forgified fabric api is in the mods folder (I took everything that wasn't a library mod of some kind out):

<img width="200" alt="mods" src="https://github.com/user-attachments/assets/3946e221-6460-4a5a-96f4-1976c4c58cd8">

If I take forgified fabric out, music comes back and it all works fine.

**Comment by Seraphim1998** [comment]
I just got the same problem, was using Sinytra Connector and it comes with forgified fabric api and I was unable to hear any music, including from jukebox.

**Comment by LZGM4702** [comment]
I have the exact same issue; I first noticed when the game was awfully quiet without any music. Apparently, they fixed it, but it must have not worked.

**Comment by Ancholio** [comment]
I'm having this same problem!

**Comment by TDEnderP** [comment]
ohh wow ok so this is sinytras fault, I hope this can be fixed soon I miss my music ;-;

**Comment by X-Machiavelli** [comment]
me too_NEOFORGE 21.0.167(MC ver_1.21)

**Comment by BrandonRosa** [comment]
same here

**Comment by EugeneLeclerc** [comment]
Same problem here.

**Comment by CaptBK13** [comment]
Why is this a problem, I can't figure out what error would disable the music

**Comment by Tapacywka** [comment]
Already reported here, it's caused by the Forgified Fabric API.
https://github.com/Sinytra/Connector/issues/1409

**Comment by murmuur22** [comment]
was this ever solved. Im also having this issue. It breaks even music discs, I assume that means the whole music engine is broken.
