### ISSUE TITLE
Tectonic incompatible crash neoforge 1.21.1

### ISSUE THREAD

**Issue by lostopkk** [Sinytra/ForgifiedFabricAPI#151]
https://github.com/Apollounknowndev/tectonic/issues/206

**Comment by NovaViper** [comment]
Can confirm the same issue on NeoForge v21.1.62 on Minecraft 1.21.1. The moment I try to create a new world or enter an existing one, it crashes immediately.

Log: https://mclo.gs/BPZVp9X
