### ISSUE TITLE
Joining a singleplayer world with forgified fabric and supplementaries causes a Network Protocol Error (Neoforge 1.21.1)

### ISSUE THREAD

**Issue by zjjohn121110** [Sinytra/ForgifiedFabricAPI#167]
Upon joining a singleplayer world with Supplementaries and forgified fabric api, the game will disconnect you from the server with a server crash log.
Only occurs when Supplementaries and Forgified are running together

[latest.log](https://github.com/user-attachments/files/17653554/latest.log)

[disconnect-2024-11-06_17.02.07-client.txt](https://github.com/user-attachments/files/17653573/disconnect-2024-11-06_17.02.07-client.txt)

**Comment by zjjohn121110** [comment]
According to the Supplementaries dev, FFAPI is altering the data jsons of the mod.
(His example) Content of one becomes "minecraft:" when it was "minecraft:bed"

**Comment by Boshigiri** [comment]
https://mclo.gs/d1Div7j
Same issues

**Comment by Machinational** [comment]
I also have the same issue.
[latest.log](https://github.com/user-attachments/files/17742527/latest.log)
[disconnect-2024-11-11_19.04.04-client.txt](https://github.com/user-attachments/files/17742528/disconnect-2024-11-11_19.04.04-client.txt)
