### ISSUE TITLE
Cannot join dedicated server with Cardinal Components API (unhandled packet: cardinal-components:entity_sync)

### ISSUE THREAD

**Issue by unilock** [Sinytra/ForgifiedFabricAPI#168]
With Cardinal Components API installed, *alongside* a Fabric mod that adds a Component that requires syncing between client and server (in this case, Trickster), the client disconnects immediately after joining a dedicated server. (singleplayer works fine)

latest.log (client): https://gist.github.com/unilock/9ea8f4888b3ecffbb023474066bb9b4d
latest.log (server): https://gist.github.com/unilock/c5f16e51b70fc77c8f14864afb8fb019

To reproduce:
1. Set up a Minecraft 1.21.1 client and server with NeoForge 21.1.77
2. Install the following mods on both sides:
- Sinytra Connector v2.0.0-beta.3+1.21.1
- Forgified Fabric API v0.104.0+2.0.18+1.21.1
- [Cardinal Components API](https://modrinth.com/mod/cardinal-components-api/version/6.1.2) v6.1.2
- Trickster (specifically [this build](https://github.com/enjarai/trickster/actions/runs/11767104576) with Sinytra Connector support)
- [Accessories](https://modrinth.com/mod/accessories/version/j6K4uRb7) v1.1.0-beta.16+1.21.1
- [CICADA](https://modrinth.com/mod/cicada/version/0.9.1+1.21-1.21.1) v0.9.1+1.21-1.21.1
- [Lavender](https://modrinth.com/mod/lavender/version/0.1.14+1.21) v0.1.14+1.21
- [owo-lib](https://modrinth.com/mod/owo-lib/version/0.12.15-beta.9+1.21) v0.12.15-beta.9+1.21
3. Start the client and the server
4. Attempt to join the server from the client
5. Disconnect due to `This server requires Cardinal Components API (unhandled packet: cardinal-components:entity_sync)`

**Comment by Su5eD** [comment]
Wasn't this fixed in 2.0.17? Or did it break again?

**Comment by unilock** [comment]
Testing v2.0.16 and v2.0.18 had the same results, as described here. v2.0.17 leads to a disconnect similar to that of https://github.com/Sinytra/ForgifiedFabricAPI/issues/166 and https://github.com/Sinytra/Connector/issues/1512 (on a dedicated server, not singleplayer!)

**Comment by unilock** [comment]
Sometimes, the game does let me join, but the server log is spammed with:

```
[Netty Server IO #1/WARN] [ne.ne.ne.ne.re.NetworkRegistry/]: No registration for payload cardinal-components:chunk_sync; refusing to decode.
[Netty Server IO #1/WARN] [ne.ne.ne.ne.re.NetworkRegistry/]: No registration for payload cardinal-components:entity_sync; refusing to decode.
```

...among similar messages for other payload types from Fabric mods.

**Comment by Moulberry** [comment]
Should be fixed by https://github.com/Sinytra/ForgifiedFabricAPI/pull/170, haven't tested

**Comment by unilock** [comment]
#170 does appear to have fixed the issue :)
