### ISSUE TITLE
Client Init for fabric mods absent

### ISSUE THREAD

**Issue by StockiesLad** [Sinytra/ForgifiedFabricAPI#181]
Using a custom model implementation doesn't work. I'm unsure of the reason, so I'll just provide the details:

Here is the Plugin:
https://github.com/StockiesLad/Carbonize/blob/main/src/main/java/net/jmb19905/CarbonizeClient.java

Here is the model itself:
https://github.com/StockiesLad/Carbonize/blob/main/src/main/java/net/jmb19905/model/CharringWoodBlockModel.java

Logs:
https://gist.github.com/StockiesLad/5e67d35defc2545b9053caa92a030b68

**Comment by StockiesLad** [comment]
After testing a bit. It doesn't even call the event `modifyModelAfterBake` at all.

**Comment by StockiesLad** [comment]
After even more testing. The Client isn't even initialising on forge and idk why

**Comment by Su5eD** [comment]
Client init for fabric mods isn't handled by ffapi. Are you running your fabric mod on forge via connector?

**Comment by StockiesLad** [comment]
> Client init for fabric mods isn't handled by ffapi. Are you running your fabric mod on forge via connector?

yeah. Everything else works fine but client init just doesn't happen for some reason. Works perfectly fine on fabric tho

**Comment by StockiesLad** [comment]
> Client init for fabric mods isn't handled by ffapi. Are you running your fabric mod on forge via connector?

yeah. Everything else works fine but client init just doesn't happen for some reason. Works perfectly fine on fabric tho

**Comment by StockiesLad** [comment]
For no apparent reason, it is working now?
