### ISSUE TITLE
can't join create mod server with FFAPI on client

### ISSUE THREAD

**Issue by kakashi1464** [Sinytra/ForgifiedFabricAPI#19]
### Describe the bug

Can't join server with FFAPI

### Steps to reproduce

1.Add FFAPI, Create, Create enchantment to mods folder
3.Run Minecraft
3.Join server

### Logs

https://mclo.gs/rL3OQUI

### Additional context

Server mod list: 
architectury-9.1.12-forge.jar
beautifiedchatserver-1.20.1-2.2.jar
betterchunkloading-1.20.1-1.9.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-6.65.jar
connectivity-1.20.1-4.4.jar
Connector-1.0.0-beta.3+1.20.1-full.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.d-1.2.6.jar
create-1.20.1-0.5.1.d.jar
cupboard-1.20.1-1.5.jar
does_potato_tick-1.20-3.6.0.jar
EverlastingSkins-1.20.1-1.0.jar
fabric-api-0.86.1+1.8.1+1.20.1.jar
ferritecore-6.0.0-forge.jar
KryptonReforged-0.2.3.jar
Ksyxis-Forge1.17-1.1.jar
lmft-1.0.2+1.20-forge.jar
mes-1.1-1.20-forge.jar
modernfix-forge-5.3.2+mc1.20.1.jar
mvs-4.0-1.20-forge.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
plasmovoice-forge-1.20.1-2.0.6.jar
polylib-forge-1200.0.2-build.85.jar
servercore-forge-1.3.7+1.20.1.jar
SimpleBackups-1.20.1-3.1.2.jar
smoothchunk-1.20.1-3.0.jar
structureessentials-1.20.1-2.9.jar
vmp-fabric-mc1.20.1-0.2.0+beta.7.101-all.jar

Client mod list:
create_enchantment_industry-1.20.1-for-create-0.5.1.d-1.2.6.jar
create-1.20.1-0.5.1.d.jar
fabric-api-0.86.1+1.8.1+1.20.1

![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/126709049/450f90c1-466d-4c7b-9223-b7a483deaf3d)

**Comment by Su5eD** [comment]
Could you retry using FFAPI `0.86.1+1.8.2+1.20.1`? I fixed a potential issue that led to the screen you got, where fabric tried to deserialize a Forge ingredient and failed, then crashed. This happened because coincidentally, both modloaders use the same marker (`-1`) for their custom ingredient packets.

**Comment by kakashi1464** [comment]
It worked! Thank you for all your hard work.
