### ISSUE TITLE
fabric api 0.87.0 keeps crashing

### ISSUE THREAD

**Issue by Art3mis-Ghub** [Sinytra/ForgifiedFabricAPI#25]
### Describe the bug

Game keeps crashing on launch, it finishes loading Forge and then it shuts down.

### Steps to reproduce

1. Install Forge 47.1.43
2. Download Forgified Fabric API latest version and place in mods folder
3. Try launching the game
...

### Logs

No crash log, only ''exit code 1''

**Comment by Su5eD** [comment]
Works for me, it properly shows the loading error screen, along with the version range error. The Forgified Fabric API requires Forge 47.1.3 specifically.

![loading error](https://github.com/Sinytra/ForgifiedFabricAPI/assets/51261569/f8f0748a-3d15-4349-b5e3-a318552df992)
