### ISSUE TITLE
Silent's mods with the sophisticated series prevent loading in a server or world.

### ISSUE THREAD

**Issue by Jacobwasbeast** [Sinytra/ForgifiedFabricAPI#26]
### Describe the bug

When a player tries to join a world/server with FFA and Silent's mods lib, gems & gear, sophisticatedcore, sophisticatedbackpacks, and sophisticatedstorage they are stuck on encrypting/ loading world and eventually kicked out with took to long to load.

### Steps to reproduce

1.Add FFA and Silent gear, lib and gems to mods folder, add sophisticatedcore, sophisticatedbackpacks, and sophisticatedstorage .
2.Launch Minecraft.
3.Load into a world or server.
4.Wait until you are kicked for took to long to load.

### Additional context

I tried this with the newest FFA and the 1.8.2 FFA. This is on Minecraft 1.20.1 and Forge 47.1.3. This does work without FFA it only occurs with FFA in the mods folder.

**Comment by Su5eD** [comment]
Please upload your debug.log file (using a paste site).

**Comment by Jacobwasbeast** [comment]
Here is the log, I added sophisticatedbackpacks, sophisticatedcore, and sophisticatedstorage into the mods folder aswell, I loaded into my survival world I already created and it disconnected me after staying on Loading World 100% for about 3 minutes.
https://pastebin.com/raw/U4gHdzEe

**Comment by Kasualix** [comment]
Your log is not debug.log but latest.log, mine [here](https://pastebin.ubuntu.com/p/KYyCqyJFMG/)
btw, FFAPI + Silent series are fine, FFAPI + sophisticated series are also fine, but the disconnection occurs with FFAPI + Silent & sophisticated series.
Maybe networking api's problem.

**Comment by Kasualix** [comment]
modlist:
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/110756250/3de3d079-713b-4dad-8cac-026ae5c9bc6b)

**Comment by Su5eD** [comment]
Fixed in 243b429989afd2c6687562419cc7fd81ab35d53a
