### ISSUE TITLE
[Suggestion] Opening version range for Forge requirement

### ISSUE THREAD

**Issue by MrKashew** [Sinytra/ForgifiedFabricAPI#30]
### Describe the bug

Run on Forge version on 1.20.1 other than 47.1.3

### Steps to reproduce

E.g. Running on forge 47.1.43, unless there is an explicit incompatibility on versions > 47.1.3
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/53996665/d3df200e-e576-4bc3-92c4-61057be0bc6a)

**Comment by Su5eD** [comment]
This is not planned for 1.20.1, see the explanation in #15

**Comment by MrKashew** [comment]
Gotcha thanks! What a shame, I hope as well it will be able to support newer versions in future, as this hard limits forge mod compatibility, perhaps with the coming of NeoForge
