### ISSUE TITLE
Smooth lighting seems broken with FFAPI, unlike FAPI

### ISSUE THREAD

**Issue by Lolothepro** [Sinytra/ForgifiedFabricAPI#31]
### Describe the bug

Indigo's fix for bug MC-197497 may be partially broken

### Steps to reproduce

Go to a world with the "-465591111666617428" generation seed
Go here: /execute in minecraft:overworld run tp @s 1732.17 -13.58 -463.76 -32.13 64.95

Fabric API:
![2023-08-26_13 57 25](https://github.com/Sinytra/ForgifiedFabricAPI/assets/68275908/d819f8ff-0d10-4d1f-8cdd-1c4d2ae98a62)

Forgified Fabric API:
![2023-08-26_13 54 11](https://github.com/Sinytra/ForgifiedFabricAPI/assets/68275908/6b2b1d0e-0568-4cb1-9d6f-aeaa27d272fd)

**Comment by Su5eD** [comment]
Looks to happen on plain Forge, too.

![](https://github.com/Sinytra/ForgifiedFabricAPI/assets/51261569/4d20f038-42f4-4c60-98dc-2183961838d0)

**Comment by Lolothepro** [comment]
caused by https://github.com/Sinytra/ForgifiedFabricAPI/commit/690539c41b915d24dbcebb3810b4b10a6c127969

**Comment by Su5eD** [comment]
Yeah I remember indigo being a significant compat problem for forge mods.

**Comment by Lolothepro** [comment]
> Yeah I remember indigo being a significant compat problem for forge mods.

Why? (do you have any examples?)

**Comment by Su5eD** [comment]
I've thought about this, and since the bug comes from vanilla, it should be fixed by mojang or forge. FFAPI's renderer does not override forge's one to prevent mod compat issues, and trying to fix issues by mixing into forge might come with unwanted side effects.
