### ISSUE TITLE
Crashes when paired with Optifine

### ISSUE THREAD

**Issue by Hitaxas** [Sinytra/ForgifiedFabricAPI#41]
### Describe the bug

This mod along with optifine causes the game to crash. 

### Steps to reproduce

1. Put forgified fabric api mod into mods folder
2. Put Optifine into mods folder
3. Boot the game
4. crash

### Logs

https://cdn.discordapp.com/attachments/463891079675117568/1151010249512337438/latest.log

**Comment by Su5eD** [comment]
Optifine is not supported. I recommend looking into alternatives such as Rubidium or Embeddium
