### ISSUE TITLE
[Missing Layer Definitions] BlockView API v2 is broken

### ISSUE THREAD

**Issue by Cixon** [Sinytra/ForgifiedFabricAPI#42]
### Describe the bug

Client Start-up failure

### Steps to reproduce

1. Download Regions Unexplored  + Terrablender (fabric)
2. Download Latest Forgified [0.88.1+1.9.10+1.20.1](https://legacy.curseforge.com/minecraft/mc-mods/forgified-fabric-api/files/4748554)
3. Sinytra ofc
4. poopbutt crash

### Logs

https://gist.github.com/Cixon/4b1cb70f0d0bb3a23628f89d451a0e0c

### Additional context

![Screenshot (130)](https://github.com/Sinytra/ForgifiedFabricAPI/assets/69068153/77105c93-2998-4ed9-9998-fb370ce978bc)

**Comment by Cixon** [comment]
for now, I will use old version

**Comment by Su5eD** [comment]
Fixed in 0.88.1+1.9.11+1.20.1
