### ISSUE TITLE
crash on boot with latest version

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/ForgifiedFabricAPI#43]
### Describe the bug

crash on boot

### Steps to reproduce

1. update api
2. boot
3.crash
...

### Logs

https://gist.github.com/Xplodin/2463cf913f3a0ac79f4e5a3bc3566958

### Additional context

mainly bclib and betternether seem to not like it but work fine on previous versions

**Comment by Matthysse** [comment]
I have the same issue, here are crashreports that I got when updating the Forgified Fabric API, when I downgraded it didn't crash anymore.
First, it crashed on boot with BetterX as described : https://pastebin.com/FqxhPh1f
Then, it crashed in game when clicking on a menu with Obscure API (forge mod) after removing the BetterX mods : https://pastebin.com/P3YQ6xxf

**Comment by Su5eD** [comment]
Fixed in 0.88.1+1.9.11+1.20.1
