### ISSUE TITLE
Instant Crash. (Exit Code 1)

### ISSUE THREAD

**Issue by Zeyeo** [Sinytra/ForgifiedFabricAPI#44]
### Describe the bug

Instant Exit Code: 1 When loading up previously working modpack

### Steps to reproduce

1. See that there is an update for my modpack
2. learn about a new fabric to forge connector auto installed into the modpack
3. say "cool" and attempt to start up
4.  Instant exit code 1
5. troubleshooting and found this mod was the issue. (fabric-api-0.88.1+1.9.11+1.20.1.jar)
6. turned off all mods except fabric-api-0.88.1+1.9.11+1.20.1.jar and got the error
7. No mods installed needed this mod just popped in
8. Would be cool to have this workin.
9. No mods are outdated.
...

### Logs

Exit Code: 1

**Comment by Su5eD** [comment]
Please provide more information, namely:
1) Forge version
2) Other mods you have installed
3) debug.log, launcher log or crash report

**Comment by Maisbohne** [comment]
try using forge 47.1.3 and not forge 47.1.30 that was my mistake and afterwards it worked

**Comment by Su5eD** [comment]
Closing as not enough information was provided to determine the issue
