### ISSUE TITLE
The mod don't work with the oldest version of Forge.

### ISSUE THREAD

**Issue by wycats0** [Sinytra/ForgifiedFabricAPI#45]
### Describe the bug

When I start the game with my modpack, the game crashes; when I start the game only with Forgified Fabric Api and Sinytra Connector, the game asks that I use Forge 47.1.3.

### Steps to reproduce

1. Start the game with a Sinytra Connector, Forgified Fabric Api and Forge 47.1.47.
[crash-2023-09-12_23.43.05-client.txt](https://github.com/Sinytra/ForgifiedFabricAPI/files/12592857/crash-2023-09-12_23.43.05-client.txt)

### Logs

https://mclo.gs/37DnEN8

**Comment by SuperStormer** [comment]
#15

**Comment by Su5eD** [comment]
Duplicate of #15
