### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by TheBeatlalo** [Sinytra/ForgifiedFabricAPI#47]
### Describe the bug

when i tried to run the game it crash afret a few seconds

### Steps to reproduce

1.open the launcher and star the game
2.the game show the monjang logo
3.after 3 or 4 seconds the game crash
...

### Additional context

i already tried to run the game without creative core and the bug still happe

mods that are instaled
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/144989630/be4e076a-6719-482f-bd75-929f83456994)

![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/144989630/df54437f-31f0-4350-8b1d-847b99ef1ec8)

**Comment by Su5eD** [comment]
Please provide your debug.log or a crash report

**Comment by enzogfaria** [comment]
remove optfine
