### ISSUE TITLE
Fluid handling Forge <> Fabric

### ISSUE THREAD

**Issue by MSandro** [Sinytra/ForgifiedFabricAPI#49]
I have tested around with Fluid piping from forge to Fabric and vice versa.
I thing #4 is not finished?
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/10937159/f79a8e60-9b09-413b-819f-24aca86a0759)

It would be great if the interaction could be improved.

**Comment by Su5eD** [comment]
What mods are you using? How can I reproduce this issue? Please provide more information

**Comment by MSandro** [comment]
I've used EnderIO (Forge) and Industrial Revolution (Fabric)

##Screenshot description:
on the bottom left, it works:
IndRev Tank -> Indrev Pipe -> EnderIO Tank
the other direction does not work.

on the right, I have the same setup, but using Fluid Conduids
I have checked a few minutes a go, all my mods are up to date.
