### ISSUE TITLE
[Server thread/ERROR] [net.minecraft.server.level.ChunkMap/]: Failed to save chunk 12,-9 java.lang.NullPointerException: World may not be null.

### ISSUE THREAD

**Issue by litjohn50** [Sinytra/ForgifiedFabricAPI#53]
### Describe the bug

Modpack creating new world on server. Crashes when trying to save with the stop cmd

### Steps to reproduce

1.
Download this modpack: https://www.curseforge.com/minecraft/modpacks/towncraft/files/4756597

2. Create a new world
3.  Generate a few chunks
4. Try to stop the world
...

Forge 1.47.3

fabric-api-0.88.1+1.9.11+1.20.1.
Connector-1.0.0-beta.14+1.20.1-full.

### Logs

https://gist.github.com/litjohn50/79b878e16a5f01c1dc05d63c89d0e3db

**Comment by Su5eD** [comment]
This is the repository for FFAPI, but you're using Connector. Please report it there.
