### ISSUE TITLE
Server crashes at startup

### ISSUE THREAD

**Issue by Foxydre1** [Sinytra/ForgifiedFabricAPI#6]
### Describe the bug

Server crashes at startup

### Steps to reproduce

Launch the server with forge 47.1.3 in 1.20.1

### Logs

https://pastebin.com/apf1PB1D

### Additional context

Hello,
We have a problem when adding ForgifiedFabricAPI to the server.

This seems to be linked to a compatibility problem with the waystone mod, which causes the server to crash on startup.

We are on version forge 47.1.3 in 1.20.1.

Thanks a lot!

**Comment by Su5eD** [comment]
By the looks of it, Balm makes a naughty move by registering creative tabs [inside](https://github.com/TwelveIterationMods/Balm/blob/2f407f0809b5b0083213733ff86103380f0b0f59/forge/src/main/java/net/blay09/mods/balm/forge/item/ForgeBalmItems.java#L72) the deferred register value getter. Vanilla itself has a check for duplicate registry entries, but it only triggers in minecraft dev environments.

Our solution is pretty simple - ignoring duplicate ID checks for non-custom registries. In the Forgified FAPI, these should be handled by Forge / Vanilla. We should care about duplicate entries in custom registries we control.
