### ISSUE TITLE
ForgifiedFabricAPI doesn't work in newer Forge version

### ISSUE THREAD

**Issue by kazumadh** [Sinytra/ForgifiedFabricAPI#63]
![forgifiedapi](https://github.com/Sinytra/ForgifiedFabricAPI/assets/140326816/baf61bf3-0bad-4bd0-8303-bf32ac0b2b7f)
Here's the crash log if necessary
[crash-2023-10-06_16.22.56-fml.txt](https://github.com/Sinytra/ForgifiedFabricAPI/files/12829356/crash-2023-10-06_16.22.56-fml.txt)

**Comment by Su5eD** [comment]
This is intended, see #15 for more information
