### ISSUE TITLE
Incompatibility with Minecolonies due to missing null check

### ISSUE THREAD

**Issue by nvb-uy** [Sinytra/ForgifiedFabricAPI#64]
### Describe the bug

Interactions with some minecolonies (forge mod) buildings cause a crash

### Steps to reproduce

1. Install Minecolonies (and dependencies) along with FFAPI
2. Progress through the mod until you have to upgrade a building (Crash was caused in the log by upgrading a University to level 2)
3. Crash happens

### Logs

https://gist.github.com/robbyv109/af018f072f92e1c5f3014458bfae5043

### Additional context

Modpack: Prominence II [FORGE].

Was discussed with Raycoms (Minecolonies dev) and says the issue has to be resolved in FFAPI

**Comment by Su5eD** [comment]
This has been fixed in a877fef0d1142e68ac2863ac304c7c5c7ab04ecf, please update to the latest FFAPI release.
