### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by NotTohm** [Sinytra/ForgifiedFabricAPI#75]
### Describe the bug

With forgified fabric enabled it crashes

### Steps to reproduce

1. start the game
2. crash

### Logs

https://paste.ee/p/BSNPY

### Additional context

probably a mod incompatibility, i can't tell though

**Comment by Su5eD** [comment]
Forgified Fabric API requires Forge 47.1.3, as described in #15

**Comment by NotTohm** [comment]
oh mb thx
