### ISSUE TITLE
[1.20.1] Crash on startup, using forge 47.1.30

### ISSUE THREAD

**Issue by leumper** [Sinytra/ForgifiedFabricAPI#77]
### Describe the bug

Crashes on startup

### Steps to reproduce

1.Install Forge 1.47.30
2.Install FFAPI
3.Crash
![image](https://github.com/Sinytra/ForgifiedFabricAPI/assets/150087004/68942c21-b962-4015-9b0f-dbb582844e7b)

### Additional context

It is told in other bug reports that Forge 47.1.3 is needed, the closest I could find was 47.1.30 (Which I still believe to be the same version), doesn't work. Am I missing a download link for Forge?

**Comment by leumper** [comment]
logs: https://pastebin.com/HdKcUVfD

**Comment by Su5eD** [comment]
FFAPI requires Forge 47.1.3 on 1.20.1, you have installed 47.1.30, which is not the same version.

**Comment by Su5eD** [comment]
See #15 for more information
