### ISSUE TITLE
[Request] Backport to 1.19.2

### ISSUE THREAD

**Issue by Zachary-Rude** [Sinytra/ForgifiedFabricAPI#78]
Hello,
I'm currently stuck on Forge 1.19.**2**, but the earliest version of this I can find is for 1.19.**4**. Would you please backport the latest version of this mod to Forge 1.19.2? It would be really helpful for people like me who still play on 1.19.2!

**Comment by Su5eD** [comment]
Backports are not planned, sorry, as explained in #20. However, the mod is open source and anyone is free to make one should they want it.
