### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by lanwoodall423** [Sinytra/ForgifiedFabricAPI#80]
### Describe the bug

Crash on launch

### Steps to reproduce

1. Install Forgified Fabric SPI 0.90.7+1.10.0
2. Launch

### Logs

https://pastebin.com/9ZB4UScp

### Additional context

This occurs with the update that just released today. Sinytra and all fabric mods are disabled.

**Comment by Su5eD** [comment]
Please upload your launcher log or crash report.

**Comment by VOLKOUL** [comment]
~~Uuuh, I don't think using FFAPI without Sinytra is a good idea. Anyway, I also get a crash on Forge 47.2.6  but with all of the mods enabled: https://github.com/Sinytra/Connector/issues/519~~

**Comment by Su5eD** [comment]
> I don't think using FFAPI without Sinytra is a good idea

FFAPI is a Forge mod like any other, there are no side effects to using it (maybe other than the forge mixin incompatibilities it had previously, but those are hopefully all fixed now)

**Comment by VOLKOUL** [comment]
Yes, yes, sorry nvm I am just blind

**Comment by VOLKOUL** [comment]
As you said it was a rootsclassic thing
