### ISSUE TITLE
Pehkui error. stops game from loading/starting up

### ISSUE THREAD

**Issue by Mordunce** [Sinytra/ForgifiedFabricAPI#86]
### Describe the bug

Error transforming Pehkui mod

### Steps to reproduce

1.Just download and try to use pehkui

### Logs

https://pastebin.com/2xrjTPuS

### Additional context

It seems like it has an issue transforming pehkui,

**Comment by Su5eD** [comment]
Use the Forge version of pehkui. This is also unrelated to FFAPI, as it's an issue with transformation done by connector as you've stated.

**Comment by Mordunce** [comment]
Thank you for your response, my intent was to use the Bewitching mod made for fabric and it requires Pehkui. I have tried using the forge version with Bewitching but it crashes the game.
