### ISSUE TITLE
Fabric Screen API crashing with JEI

### ISSUE THREAD

**Issue by LiterallyAidan** [Sinytra/ForgifiedFabricAPI#89]
### Describe the bug

When I use JEI on modded items the Fabric Screen API crashes my game and I was wondering if there way a way to fix that

### Steps to reproduce

1. I open my inventory and look for the item im trying to find in JEI
2. I click on a modded item and look at the recipe
3. When I close the menu, the game crashes
...

### Logs

https://pastebin.com/5wXytU0S

**Comment by Su5eD** [comment]
Please specify "modded items". Which mods are you using?

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce.

If you can provide the necessary logs and information to reproduce the problem or identify the faulty mod, please open a new issue with all necessary details.
