### ISSUE TITLE
Issue that causes a crash.

### ISSUE THREAD

**Issue by PercyJames** [Sinytra/ForgifiedFabricAPI#94]
### Describe the bug

When I try to load my pack it crashes.

### Steps to reproduce

1. 
2.
3.
...

### Logs

https://pastebin.com/GmEnF2nQ

**Comment by Su5eD** [comment]
> [16:19:34] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'tfc', Requested by: 'chiselsandbits_tfc', Expected range: '[3.1.0,)', Actual version: '[MISSING]'
	Mod ID: 'forge', Requested by: 'zoobox', Expected range: '[47.2.6,47.2.6]', Actual version: '47.2.20'
	Mod ID: 'farmersdelight', Requested by: 'farmersrespite', Expected range: '[1.19,1.20)', Actual version: '1.20.1-1.2.3'
	Mod ID: 'forge', Requested by: 'ctov', Expected range: '[48,)', Actual version: '47.2.20'
	Mod ID: 'minecraft', Requested by: 'farmersrespite', Expected range: '[1.19,1.20)', Actual version: '1.20.1'
	Mod ID: 'jei', Requested by: 'jeresources', Expected range: '[15.2.0,)', Actual version: '[MISSING]'
	Mod ID: 'minecraft', Requested by: 'archaeology', Expected range: '[1.19.2,1.20)', Actual version: '1.20.1'
